name: Rust

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests (default features)
      run: cargo test --verbose
    - name: Run tests (all features)
      run: cargo test --verbose --all-features
    - name: Build docs
      run: cargo doc --no-deps --verbose
